### ISSUE TITLE
Display API and websocket status on interface

### ISSUE THREAD

**Issue by beraldoleal** [kytos/kytos-admin-ui#16]
For now, on the left menu at the bottom, display two informations in form of "leds". To inform the user when the API endpoint is working and the websocket too.

**Comment by beraldoleal** [comment]
@diraol I saw the icons, nice. But is working already ? Seems like is not.

**Comment by diraol** [comment]
@beraldoleal for me it seems to be working.... why not?

**Comment by beraldoleal** [comment]
I didn't saw your PR on kyco repo. Thanks, is working.
