### ISSUE TITLE
Fix strange logs (like a binary?)

### ISSUE THREAD

**Issue by beraldoleal** [kytos/kytos-admin-ui#31]
![print](https://cloud.githubusercontent.com/assets/49336/20143111/ce0de95a-a67e-11e6-8bcd-63e2603961b3.png)

**Comment by beraldoleal** [comment]
@diraol @macartur did you guys fix this ?

**Comment by macartur** [comment]
I can't repeat this, I tried put a binary string in log and don't showed this.

**Comment by beraldoleal** [comment]
I think that is fixed ... i will close this. thanks.
